<?xml version="1.0" encoding="utf-8"?><Database Name="ProjectV2" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ProjectV2;Integrated Security=True" SettingsObjectName="ProjectRK.My.MySettings" SettingsPropertyName="ProjectV2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.TEST" Member="TESTs">
    <Type Name="TEST">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MONEY" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CBID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CategoryBalance_TEST" Member="CategoryBalance" ThisKey="CBID" OtherKey="CBID" Type="CategoryBalance" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoriesD" Member="CategoriesDs">
    <Type Name="CategoriesD">
      <Column Name="CategoryDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryDName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CategoriesD_OrdersDetailsD" Member="OrdersDetailsDs" ThisKey="CategoryDID" OtherKey="CategoryDID" Type="OrdersDetailsD" />
    </Type>
  </Table>
  <Table Name="dbo.CategoriesE" Member="CategoriesEs">
    <Type Name="CategoriesE">
      <Column Name="CategoryEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryEName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CategoriesE_OrdersDetailsE" Member="OrdersDetailsEs" ThisKey="CategoryEID" OtherKey="CategoryEID" Type="OrdersDetailsE" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryBalance" Member="CategoryBalances">
    <Type Name="CategoryBalance">
      <Column Name="CBID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CBNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CategoryBalance_TEST" Member="TESTs" ThisKey="CBID" OtherKey="CBID" Type="TEST" />
      <Association Name="CategoryBalance_Order" Member="Orders" ThisKey="CBID" OtherKey="CBID" Type="Order" />
      <Association Name="CategoryBalance_OrdersD" Member="OrdersDs" ThisKey="CBID" OtherKey="CBID" Type="OrdersD" />
      <Association Name="CategoryBalance_OrdersE" Member="OrdersEs" ThisKey="CBID" OtherKey="CBID" Type="OrdersE" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="CustomerID" OtherKey="CustomerID" Type="Order" />
      <Association Name="Customer_OrdersD" Member="OrdersDs" ThisKey="CustomerID" OtherKey="CustomerID" Type="OrdersD" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Employee_Order" Member="Orders" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Order" />
      <Association Name="Employee_OrdersD" Member="OrdersDs" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="OrdersD" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CBID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrdersDetail" Member="OrdersDetails" ThisKey="OrderID" OtherKey="OrderID" Type="OrdersDetail" />
      <Association Name="CategoryBalance_Order" Member="CategoryBalance" ThisKey="CBID" OtherKey="CBID" Type="CategoryBalance" IsForeignKey="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersD" Member="OrdersDs">
    <Type Name="OrdersD">
      <Column Name="OrderDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CBID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrdersD_OrdersDetailsD" Member="OrdersDetailsDs" ThisKey="OrderDID" OtherKey="OrderDID" Type="OrdersDetailsD" />
      <Association Name="CategoryBalance_OrdersD" Member="CategoryBalance" ThisKey="CBID" OtherKey="CBID" Type="CategoryBalance" IsForeignKey="true" />
      <Association Name="Customer_OrdersD" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_OrdersD" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersDetails" Member="OrdersDetails">
    <Type Name="OrdersDetail">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Order_OrdersDetail" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrdersDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersDetailsD" Member="OrdersDetailsDs">
    <Type Name="OrdersDetailsD">
      <Column Name="OrderDID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryDID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Donation" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="CategoriesD_OrdersDetailsD" Member="CategoriesD" ThisKey="CategoryDID" OtherKey="CategoryDID" Type="CategoriesD" IsForeignKey="true" />
      <Association Name="OrdersD_OrdersDetailsD" Member="OrdersD" ThisKey="OrderDID" OtherKey="OrderDID" Type="OrdersD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersDetailsE" Member="OrdersDetailsEs">
    <Type Name="OrdersDetailsE">
      <Column Name="OrderEID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryEID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="CategoriesE_OrdersDetailsE" Member="CategoriesE" ThisKey="CategoryEID" OtherKey="CategoryEID" Type="CategoriesE" IsForeignKey="true" />
      <Association Name="OrdersE_OrdersDetailsE" Member="OrdersE" ThisKey="OrderEID" OtherKey="OrderEID" Type="OrdersE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersE" Member="OrdersEs">
    <Type Name="OrdersE">
      <Column Name="OrderEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderEDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CBID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrdersE_OrdersDetailsE" Member="OrdersDetailsEs" ThisKey="OrderEID" OtherKey="OrderEID" Type="OrdersDetailsE" />
      <Association Name="CategoryBalance_OrdersE" Member="CategoryBalance" ThisKey="CBID" OtherKey="CBID" Type="CategoryBalance" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityPerUnit" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_OrdersDetail" Member="OrdersDetails" ThisKey="ProductID" OtherKey="ProductID" Type="OrdersDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>